name: CI AT

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate
        run: bash -n ./appmonitor/status-check.sh || echo "::error::Falha ao validar o script"

  Test:
    needs: [Validate]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Running tests" && exit 0

  Package:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Report
        run: mkdir -p reports && echo "Teste e validação bem sucedidos" > reports/relatorio.txt

      - name: Compact
        run: zip -r report.zip reports

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: relatorio
          path: report.zip
    
  summary:
    runs-on: ubuntu-latest
    needs: [Validate, Test, Package]
    if: always()

    steps:
      - name: Set summary content
        run: |
          echo "# CI Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "- OS: ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Validate: ${{ needs.Validate.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Test: ${{ needs.Test.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Package: ${{ needs.Package.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Artifact: https://github.com/jvcmtr/DevOps_AT/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY